---
language: generic
os:
  - osx
  - linux

env:
  global:
    - OC_URL_STEM="https://github.com/sourceryinstitute/OpenCoarrays/releases/download"
    - OC_VER="2.3.1"
    - CTEST_OUTPUT_ON_FAILURE=ON
    - CMAKE_VER="3.12.4"
    - CMAKE_URL_STEM="https://cmake.org/files"
    - PATH="${HOME}/.local/bin:${PATH}"

addons:
  homebrew:
    brewfile: Brewfile.travis
    update: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - gfortran-8
      - libopenmpi-dev
      - openmpi-bin
      - openmpi-common

install:
  - export FC=gfortran-8
  - export CC=gcc-8
  - brew link --overwrite gcc || true
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && export FC=gfortran-8 || true'
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && export CC=gcc-8 || true'
  - $FC --version
  - $CC --version
  - '[ "${TRAVIS_OS_NAME}" = "linux" ] && wget "${CMAKE_URL_STEM}/v${CMAKE_VER%.*}/cmake-${CMAKE_VER}-Linux-x86_64.sh" || true'
  - 'bash cmake-${CMAKE_VER}-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=${HOME}/.local || true'
  - '[ "${TRAVIS_OS_NAME}" = "linux" ] && wget "${OC_URL_STEM}/${OC_VER}/OpenCoarrays-${OC_VER}.tar.gz" || true'
  - '[ "${TRAVIS_OS_NAME}" = "linux" ] && tar xzvf "OpenCoarrays-${OC_VER}.tar.gz" || true'
  - mkdir -p "OpenCoarrays-${OC_VER}/build" || true
  - cd OpenCoarrays-${OC_VER}/build || true
  - '[ "${TRAVIS_OS_NAME}" = "linux" ] && cmake -DCMAKE_INSTALL_PREFIX=${HOME}/.local .. || true'
  - '[ "${TRAVIS_OS_NAME}" = "linux" ] && make -j 3 || true'
  - '[ "${TRAVIS_OS_NAME}" = "linux" ] && make install || true'
  - which caf && export FC=caf
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release
  - ctest --output-on-failure
